gfx/env/backalleybk.tga
gfx/env/backalleydn.tga
gfx/env/backalleyft.tga
gfx/env/backalleylf.tga
gfx/env/backalleyrt.tga
gfx/env/backalleyup.tga
halflife.wad
models/zp_industry/hessi_bank.mdl
models/zp_industry/xen_barrel2_2.mdl
models/zp_industry/xen_barrel5_2.mdl
models/zp_industry/xen_car2_2.mdl
models/zp_industry/xen_car4_2.mdl
models/zp_industry/xen_fork.mdl
models/zp_industry/xen_trailer.mdl
models/zp_industry/xen_trashcan.mdl
models/zp_industry/xen_tree1.mdl
models/zp_industry/xen_van5_2.mdl
sound/cs_rhs22/ambient_summer.wav
sound/cs_rhs22/creak.wav
sound/cs_rhs22/sus.wav
sound/cs_rhs22/windy.wav
sprites/ballsmoke.spr
sprites/glow01.spr
sprites/yelflare1.spr
maps/zp_industry.txt
maps/zp_industry.res
