gfx/env/duskbk.tga
gfx/env/duskdn.tga
gfx/env/duskft.tga
gfx/env/dusklf.tga
gfx/env/duskrt.tga
gfx/env/duskup.tga
models/zp_santeria/super_being.mdl
sound/cs_rhs22/windy.wav
sound/zp_santeria/Radio.wav
sprites/glow01.spr
sprites/haze.spr
sprites/zp_santeria/3dm_leaves1.spr
sprites/zp_santeria/3dm_leaves2.spr
sprites/zp_santeria/santglow1.spr
sprites/zp_santeria/santglow2.spr
maps/zp_santeria.txt
maps/zp_santeria.res
