; APIs
amxx-modding-kit/api_custom_weapons.amxx
amxx-modding-kit/api_custom_entities.amxx
amxx-modding-kit/api_player_model.amxx
amxx-modding-kit/api_rounds.amxx
amxx-modding-kit/api_waypoint_markers.amxx
amxx-modding-kit/api_entity_force.amxx
amxx-modding-kit/api_states.amxx
amxx-modding-kit/api_assets.amxx
amxx-modding-kit/api_player_roles.amxx
amxx-modding-kit/api_custom_events.amxx
amxx-modding-kit/api_player_music.amxx
amxx-modding-kit/weapon_base_throwable.amxx


; Entity Extensions
zombiepanic/entities/extensions/func_breakable.amxx
zombiepanic/entities/extensions/func_door.amxx
zombiepanic/entities/extensions/func_button.amxx
zombiepanic/entities/extensions/func_train.amxx
zombiepanic/entities/extensions/func_wall_toggle.amxx
zombiepanic/entities/extensions/multi_manager.amxx
zombiepanic/entities/extensions/multisource.amxx
zombiepanic/entities/extensions/ambient_generic.amxx
zombiepanic/entities/extensions/weaponbox.amxx

; Entities
zombiepanic/entities/base_item.amxx
zombiepanic/entities/base_spawner.amxx
zombiepanic/entities/spawners/ammo_spawner.amxx
zombiepanic/entities/spawners/weapon_spawner.amxx
zombiepanic/entities/charges/satchel_charge.amxx
zombiepanic/entities/charges/grenade.amxx
zombiepanic/entities/info_player_team.amxx
zombiepanic/entities/triggers/trigger_endround.amxx
zombiepanic/entities/items/item_armor.amxx
zombiepanic/entities/items/item_healthkit.amxx
zombiepanic/entities/spawners/ammos/ammo_9mmclip.amxx
zombiepanic/entities/spawners/ammos/ammo_357.amxx
zombiepanic/entities/spawners/ammos/ammo_556ar.amxx
zombiepanic/entities/spawners/ammos/ammo_556box.amxx
zombiepanic/entities/spawners/ammos/ammo_buckshot.amxx
zombiepanic/entities/spawners/weapons/weapon_357.amxx
zombiepanic/entities/spawners/weapons/weapon_556ar.amxx
zombiepanic/entities/spawners/weapons/weapon_handgrenade.amxx
zombiepanic/entities/spawners/weapons/weapon_satchel.amxx
zombiepanic/entities/spawners/weapons/weapon_shotgun.amxx
zombiepanic/entities/spawners/weapons/weapon_9mmhandgun.amxx
zombiepanic/entities/spawners/weapons/weapon_crowbar.amxx
zombiepanic/entities/effects/lightcone.amxx

; Weapons
zombiepanic/weapons/base.amxx
zombiepanic/weapons/base_grenade.amxx
zombiepanic/weapons/swipe.amxx
zombiepanic/weapons/556ar.amxx
zombiepanic/weapons/9mmhandgun.amxx
zombiepanic/weapons/357.amxx
zombiepanic/weapons/crowbar.amxx
zombiepanic/weapons/shotgun.amxx
zombiepanic/weapons/satchel.amxx
zombiepanic/weapons/handgrenade.amxx

; Core
zombiepanic/core/core.amxx
zombiepanic/core/gamerules.amxx
zombiepanic/core/ammo.amxx
zombiepanic/core/hud.amxx
zombiepanic/core/gamemodes.amxx

; Features
zombiepanic/features/infection.amxx
zombiepanic/features/characters.amxx
zombiepanic/features/use_pickup.amxx
zombiepanic/features/music.amxx
zombiepanic/features/panic.amxx
zombiepanic/features/zombie_vision.amxx
zombiepanic/features/flashlight.amxx
zombiepanic/features/winmessage.amxx

; Game Modes
zombiepanic/gamemodes/survival.amxx
zombiepanic/gamemodes/objective.amxx

; Player Roles
zombiepanic/player-roles/base.amxx
zombiepanic/player-roles/survivor.amxx
zombiepanic/player-roles/zombie.amxx

; Extra
zombiepanic/extra/objective_marks.amxx
zombiepanic/extra/hints.amxx
zombiepanic/extra/bot_fixes.amxx
zombiepanic/extra/mapinfo.amxx
